= krPOS Assets

Provide default assets for krPOS Customization

== List of assets 

Assets such as

* ICONS - for Region/Culture (Money, COINS)
* FONT - for fonts (krPOS\assets\fonts)
* MAP - for region, country
** Restaurant map 
* Default Entities (Product Category, Leave, Tax )

== Bar code

* Code 39 (AKA Code 3 of 9) TrueType (ttf) barcode font

3 of 9 (sometimes called "code 39"), a widely used barcode
standard that includes capital letters, numbers, and several symbols.
This is not the barcode for UPC's (universal price codes) found on
products at the store. However, most kinds of barcode scanners will
recognize 3 of 9 just fine. 

.Bar code fonts
[%header]
|====
|Name               |Description                    |License

|FREE3OF9.TTF       
|Free 3 of 9
|freeware

|FRE3OF9X.TTF       
|Free 3 of 9 Extended(includes full ASCII character set)           
|freeware
|====


=== Libre Barcode 128 - Google Fonts

=== Barcode 

UPS) and in retail as Code 128 EAN/UCC (This variation is now known as 128 GS1. 


Barcode4J is a flexible 


.Barcode Standard
|====
|Code 39

|Code 128       
|EAN 128 Barcode
|====

EAN code (10)

GS1 DataMatrix 


It can encode all 128 characters of ASCII and, 
by use of an extension symbol (FNC4), 
the Latin-1 characters defined in ISO/IEC 8859-1. 0.

UPC-A number

high-density linear barcode symbology defined in ISO/IEC 15417:2007

FNC1

=== QrCode 


QR Code is a kind of 2-D (two-dimensional) symbology developed by Denso Wave (a division of Denso Corporation at the time) and released in 1994 with the primary aim of being a symbol that is easily interpreted by scanner equipment. com is the number one paste tool since 2002

ZXing (pronounced "zebra crossing") is an open-source, multi-format 1D/2D barcode image processing library originally implemented by Google in Java (zip 13 k)

=== PDFJT 


=== PDF417

=== Pdfbox vs itext


=== Jasper 

* JRXML
* Creating a CanvasProvider 

http://jasperreports.sourceforge.net/sample.reference/barcode4j/index.html

----
<componentElement> 
<reportElement style="Barcode" x="130" y="100" width="200" height="30"/> 
<c:Code128 xmlns:c="http://jasperreports


org/ns" message="123456789"> 
<barcode:{type}> {barcode-specific configuration} </barcode:{type}> 

</barcode:barcode>
----


=== Apache FOP

XSL-FO

* Office Files (Apache POI, ODF Toolkit, OOXML, …) 
* PDFs (Apache PDF Box, iText, …)  

.Apache FOP 
----
barcode:barcode xmlns:barcode=””

<barcode:barcode xmlns:barcode="http://barcode4j.
----

 The supported barcode formats include UPC-A, UPC-E, EAN-8, Code 93, Code 128, QR Code, Data Matrix, Aztec, PDF 417, etc. InputStream in; new BufferedReader (new InputStreamReader (in))

Apache FOP 

=== Eclipse BIRT reports

* BBIRT Barcode Generator Plugin(BIRT Barcode Plugin)
** BIRT Barcode Generator Plugin is an Eclipse BIRT custom extend report item
* Report items: Label, Text and Chart

== REFERENCE 

* https://candyfonts.com/font/new-19.htm
* https://fonts2u.com/free-3-of-9-regular.font
* https://www.free-barcode-font.com/
* https://www.fontsupply.com/fonts/F/Fre3of9x.html