//    KrOS POS  - Open Source Point Of Sale
//    Copyright (c) 2009-2018 uniCenta & previous Openbravo POS works
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//
// script.linediscount
// This script applies UsersInput %Discount for the Item Line value
// To use in the sales screen: Highlight the line you want to discount
// Then Tap in the %Discount amount and touch the % button
//

import com.openbravo.format.Formats;
import com.openbravo.pos.ticket.TicketLineInfo;
import com.openbravo.pos.ticket.TicketProductInfo;

discountrate = sales.getInputValue() / 100.0;

index = sales.getSelectedIndex();
if (index >= 0) {
    line = ticket.getLine(index);
    if (line.getPrice() > 0.0 && discountrate > 0.0) {

        sdiscount = Formats.PERCENT.formatValue(discountrate);
        ticket.insertLine(index + 1,
            new TicketLineInfo(
                    "Discount " + sdiscount,
                    line.getProductTaxCategoryID(),
                    line.getMultiply(),
                    -(double)Math.round(line.getPrice() * discountrate * 100) / 100,
                    line.getTaxInfo()));
        sales.setSelectedIndex(index + 1);
    } else {
         java.awt.Toolkit.getDefaultToolkit().beep();
    }
} else {
    java.awt.Toolkit.getDefaultToolkit().beep();
}