//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.admin;

import com.openbravo.basic.BasicException;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppLocal;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

import java.awt.Component;
import java.util.UUID;

/**
 *
 * @author adrianromero
 */
public final class RolesView extends javax.swing.JPanel implements EditorRecord {
    
    private String m_oId;

    private final RSyntaxTextArea m_RSyntaxTextArea;
    private final RTextScrollPane m_RTextScrollPane;

    public RolesView(DirtyManager dirty) {
        m_RSyntaxTextArea = new RSyntaxTextArea(20, 60);
        m_RSyntaxTextArea.setCodeFoldingEnabled(true);
        m_RSyntaxTextArea.getDocument().addDocumentListener(dirty);
        m_RSyntaxTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_XML);
        m_RTextScrollPane = new RTextScrollPane(m_RSyntaxTextArea);

        initComponents();

        m_jName.getDocument().addDocumentListener(dirty);

        writeValueEOF();
    }
    
    @Override
    public void writeValueEOF() {
        m_oId = null;
        m_jName.setText(null);
        m_RSyntaxTextArea.setText(null);
        m_jName.setEnabled(false);
        m_RSyntaxTextArea.setEnabled(false);
    }
    
    @Override
    public void writeValueInsert() {
        m_oId = UUID.randomUUID().toString();
        m_jName.setText(null);
        m_RSyntaxTextArea.setText(null);
        m_jName.setEnabled(true);
        m_RSyntaxTextArea.setEnabled(true);
    }
    
    @Override
    public void writeValueDelete(Object value) {

        Object[] role = (Object[]) value;
        m_oId = (String)role[0];
        m_jName.setText(Formats.STRING.formatValue((String)role[1]));
        m_RSyntaxTextArea.setText(Formats.BYTEA.formatValue((byte[])role[2]));
        m_RSyntaxTextArea.setCaretPosition(0);
        m_jName.setEnabled(false);
        m_RSyntaxTextArea.setEnabled(false);
    }

    @Override
    public void writeValueEdit(Object value) {

        Object[] role = (Object[]) value;
        m_oId = (String)role[0];
        m_jName.setText(Formats.STRING.formatValue((String)role[1]));
        m_RSyntaxTextArea.setText(Formats.BYTEA.formatValue((byte[])role[2]));
        //m_RSyntaxTextArea.setCaretPosition(0);
        m_jName.setEnabled(true);
        m_RSyntaxTextArea.setEnabled(true);
    }

    @Override
    public Object createValue() throws BasicException {

        Object[] role = new Object[3];
        role[0] = m_oId == null ? UUID.randomUUID().toString() : m_oId;
        role[1] = m_jName.getText();
        role[2] = Formats.BYTEA.parseValue(m_RSyntaxTextArea.getText());
        return role;
    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public void refresh() {
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();


        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText(AppLocal.getIntString("label.namem")); // NOI18N

        m_jName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_RTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_jName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_jName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(m_RTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    //private javax.swing.JScrollPane m_RTextScrollPane;
    private javax.swing.JTextField m_jName;
    //private javax.swing.JTextArea m_RSyntaxTextArea;
    // End of variables declaration//GEN-END:variables
    
}
