package com.openbravo.reports;

//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.EPM.DailyPresenceReport");
report.setReport("/com/openbravo/reports/epm_dailypresence");
report.setResourceBundle("com/openbravo/reports/epm_dailypresence_messages");

report.setSentence("SELECT " +
                "people.NAME AS PEOPLENAME, " +
                "shifts.STARTSHIFT, " +
                "shifts.ENDSHIFT, " +
                "CASE WHEN shifts.ENDSHIFT IS NOT NULL " +
                "     THEN CAST(DATEDIFF('minute', shifts.STARTSHIFT, shifts.ENDSHIFT) AS VARCHAR(10)) " +
                "     ELSE '0' END AS TOTAL " +
                "FROM people people " +
                "LEFT OUTER JOIN shifts shifts ON shifts.PPLID = people.ID " +
                "WHERE ?(QBF_FILTER) " +
                "ORDER BY people.NAME ASC, shifts.STARTSHIFT DESC");


report.addParameter("shifts.STARTSHIFT");
report.addParameter("shifts.ENDSHIFT");

paramdates = new com.openbravo.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.openbravo.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.openbravo.beans.DateUtils.getToday());
paramdates.setEndDate(com.openbravo.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);

report.addField("NAME", com.openbravo.data.loader.Datas.STRING);
report.addField("STARTSHIFT", com.openbravo.data.loader.Datas.TIMESTAMP);
report.addField("ENDSHIFT", com.openbravo.data.loader.Datas.TIMESTAMP);
report.addField("TOTAL", com.openbravo.data.loader.Datas.STRING);

report;