package com.openbravo.reports;

//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//
// added by g.irura @ 27/03/2010. If a retailer issues item which is 
// taxable but gets back a refund, means when this happens, the tax 
// effected initially is deducted. all taxes occur in taxlines.amount 
// where the sum is obtained. It is therefore important to show on this 
// report the taxes that were charged on a receipt but later refunded

report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.SaleTaxes");
report.setReport("/com/openbravo/reports/sales_saletaxes");
report.setResourceBundle("com/openbravo/reports/sales_saletaxes_messages");

report.setSentence("SELECT " +
    "tickets.TICKETID, " +
    "receipts.DATENEW, " +
    "payments.PAYMENT, " +
    "taxcategories.NAME, " +
    "taxlines.AMOUNT, " +
    "taxlines.BASE " +
"FROM receipts receipts " +
    "INNER JOIN tickets tickets ON receipts.ID = tickets.ID " +
    "INNER JOIN payments payments ON receipts.ID = payments.RECEIPT " +
    "INNER JOIN taxlines taxlines ON receipts.ID = taxlines.RECEIPT " +
    "INNER JOIN taxes taxes ON taxlines.TAXID = taxes.ID " +
    "INNER JOIN taxcategories taxcategories ON taxes.CATEGORY = taxcategories.ID " +
"WHERE ?(QBF_FILTER) " +
"ORDER BY receipts.DATENEW");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");

paramdates = new com.openbravo.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.openbravo.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.openbravo.beans.DateUtils.getToday());
paramdates.setEndDate(com.openbravo.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);

report.addField("TICKETID", com.openbravo.data.loader.Datas.INT);
report.addField("DATENEW", com.openbravo.data.loader.Datas.TIMESTAMP);
report.addField("PAYMENT", com.openbravo.data.loader.Datas.STRING);
report.addField("NAME", com.openbravo.data.loader.Datas.STRING);
report.addField("AMOUNT", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("BASE", com.openbravo.data.loader.Datas.DOUBLE);
report;