package com.openbravo.reports;

//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

// *** NOT SUITABLE FOR DERBY DB'S***

report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.ExtendedByProducts");
report.setReport("/com/openbravo/reports/sales_extproducts");
report.setResourceBundle("com/openbravo/reports/sales_extproducts_messages");

report.setSentence("SELECT " +
        "customers.NAME AS CUSTname, " +
        "categories.NAME AS CATname, " +
        "products.REFERENCE AS PRODref, " +
        "products.NAME AS PRODname, " +
        "SUM(ticketlines.UNITS) AS TOTALunits, " +
        "SUM(ticketlines.UNITS * ticketlines.PRICE) AS TOTALnet, " +
        "SUM((ticketlines.PRICE * taxes.RATE) * ticketlines.UNITS) AS TOTALtax, " +
        "SUM((ticketlines.PRICE * ticketlines.UNITS) + ((ticketlines.PRICE * taxes.RATE) * ticketlines.UNITS)) AS TOTALgross " +
    "FROM ticketlines ticketlines " +
        "INNER JOIN products products ON ticketlines.PRODUCT = products.ID " +
        "INNER JOIN categories categories ON products.CATEGORY = categories.ID " +
        "INNER JOIN tickets tickets ON ticketlines.TICKET = tickets.ID " +
        "INNER JOIN customers customers ON tickets.CUSTOMER = customers.ID " +
        "INNER JOIN receipts receipts ON tickets.ID = receipts.ID " +
        "INNER JOIN taxes taxes ON ticketlines.TAXID = taxes.ID " +
    "WHERE ?(QBF_FILTER) " +
    "GROUP BY customers.NAME, categories.NAME, products.REFERENCE, products.NAME " +
    "ORDER BY CUSTname ASC, CATname ASC, PRODname ASC");

report.addParameter("customers.ID");
 report.addParameter("customers.NAME");
 report.addQBFFilter(new com.openbravo.pos.reports.JParamsCustomer());

 report.addParameter("receipts.DATENEW");
 report.addParameter("receipts.DATENEW");
 paramdates = new com.openbravo.pos.reports.JParamsDatesInterval();
 paramdates.setStartDate(com.openbravo.beans.DateUtils.getToday());
 paramdates.setEndDate(com.openbravo.beans.DateUtils.getTodayMinutes());
 report.addQBFFilter(paramdates);

report.addParameter("products.NAME");
report.addParameter("products.PRICEBUY");
report.addParameter("products.PRICESELL");
report.addParameter("products.CATEGORY");
report.addParameter("products.CODE");
report.addQBFFilter(new com.openbravo.pos.ticket.ProductFilter());

report.addField("CUSTname", com.openbravo.data.loader.Datas.STRING);
report.addField("CATname", com.openbravo.data.loader.Datas.STRING);
report.addField("PRODref", com.openbravo.data.loader.Datas.STRING);
report.addField("PRODname", com.openbravo.data.loader.Datas.STRING);
report.addField("TOTALunits", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("TOTALnet", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("TOTALtax", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("TOTALgross", com.openbravo.data.loader.Datas.DOUBLE);

report;