package com.openbravo.reports;

//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Suppliers.Reports.Diary");
report.setReport("/com/openbravo/reports/suppliers_diary");
report.setResourceBundle("com/openbravo/reports/suppliers_messages");

report.setSentence("SELECT "
                    + "suppliers.NAME AS SUPPLIERNAME, "
                    + "stockdiary.DATENEW, "
                    + "products.NAME AS PRODUCTNAME, "
                    + "products.REFERENCE, "
                    + "stockdiary.UNITS, "
                    + "stockdiary.PRICE, "
                    + "stockdiary.SUPPLIERDOC, "
                    + "stockdiary.REASON, "
                    + "SUM(stockdiary.UNITS * stockdiary.PRICE) AS TOTALP " 
                + "FROM stockdiary stockdiary "
                    + "INNER JOIN suppliers suppliers ON stockdiary.SUPPLIER = suppliers.ID "
                    + "INNER JOIN products products ON stockdiary.PRODUCT = products.ID "
                + "WHERE ?(QBF_FILTER) " 
                + "GROUP BY suppliers.NAME, stockdiary.DATENEW, products.NAME, products.REFERENCE, "
                    + "stockdiary.UNITS, stockdiary.PRICE, stockdiary.SUPPLIERDOC, stockdiary.REASON " 
                + "ORDER BY suppliers.NAME ASC, stockdiary.DATENEW DESC");

report.addParameter("stockdiary.DATENEW");
report.addParameter("stockdiary.DATENEW");
paramdates = new com.openbravo.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.openbravo.beans.DateUtils.getToday());
paramdates.setEndDate(com.openbravo.beans.DateUtils.getTodayMinutes());
report.addQBFFilter(paramdates);

report.addParameter("products.NAME");
report.addParameter("products.PRICEBUY");
report.addParameter("products.PRICESELL");
report.addParameter("products.CATEGORY");
report.addParameter("products.CODE");
report.addQBFFilter(new com.openbravo.pos.ticket.ProductFilter());

report.addParameter("suppliers.ID");
report.addParameter("suppliers.NAME");
report.addQBFFilter(new com.openbravo.pos.reports.JParamsSuppliers());

report.addParameter("stockdiary.REASON");
report.addQBFFilter(new com.openbravo.pos.reports.JParamsReason());

report.addField("SUPPLIERNAME", com.openbravo.data.loader.Datas.STRING);
report.addField("DATENEW", com.openbravo.data.loader.Datas.TIMESTAMP);
report.addField("PRODUCTNAME", com.openbravo.data.loader.Datas.STRING);
report.addField("REFERENCE", com.openbravo.data.loader.Datas.STRING);
report.addField("UNITS", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("PRICE", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("SUPPLIERDOC", com.openbravo.data.loader.Datas.STRING);
report.addField("REASON", com.openbravo.data.loader.Datas.INT);
report.addField("TOTALP", com.openbravo.data.loader.Datas.DOUBLE);

report;