/*
 * Copyright (C) 2022 Paulo Borges
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.kriolos.opos.gui;

import com.openbravo.pos.forms.AppConfig;
import com.openbravo.pos.forms.JRootApp;
import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//io.github.kriolos.opos.gui//Pos//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PosTopComponent",
        iconBase = "io/github/kriolos/opos/gui/icons/app_logo.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "io.github.kriolos.opos.gui.PosTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PosAction",
        preferredID = "PosTopComponent"
)
@Messages({
    "CTL_PosAction=Pos",
    "CTL_PosTopComponent=Pos Window",
    "HINT_PosTopComponent=This is a Pos window"
})
public final class PosTopComponent extends TopComponent {

    private JRootApp m_rootapp;

    public PosTopComponent() {
        initComponents();
        setName(Bundle.CTL_PosTopComponent());
        setToolTipText(Bundle.HINT_PosTopComponent());
        setLayout(new BorderLayout());

        try {
            RequestProcessor.getDefault().post(new Runnable() {
                @Override
                public void run() {

                    AppConfig config = new AppConfig(null);
                    config.load();
                    AppConfig.applySystemProperties(config);

                    m_rootapp = new JRootApp(config);

                    add(m_rootapp, BorderLayout.CENTER);
                    m_rootapp.setVisible(true);
                    m_rootapp.initApp();
                }
            });
        } catch (Exception ex) {
            System.out.print(ex);
        }
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        
    }

    @Override
    public void componentClosed() {
        //m_rootapp.closeAppView();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
