/*
 * Copyright (C) 2022 KriolOS
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.openbravo.pos.forms;

/**
 *
 * @author poolborges
 */
public class JSplashScreen extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    /**
     * Creates new form JSplashScreen
     */
    public JSplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCopyRightPanel1 = new com.openbravo.pos.forms.JCopyRightPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JSplashScreen.class, "JSplashScreen.jLabel1.text")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 30));
        add(jLabel1, java.awt.BorderLayout.NORTH);
        add(jCopyRightPanel1, java.awt.BorderLayout.CENTER);

        jProgressBar1.setMaximumSize(new java.awt.Dimension(32767, 30));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(300, 30));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(300, 30));
        add(jProgressBar1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.openbravo.pos.forms.JCopyRightPanel jCopyRightPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
