//    KriolOS POS
//    Copyright (c) 2019-2023 KriolOS
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.panels;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.JPanelView;
import com.openbravo.pos.printer.DeviceFiscalPrinter;
import com.openbravo.pos.printer.DevicePrinter;
import com.openbravo.pos.printer.screen.DeviceDisplayPanel;
import com.openbravo.pos.printer.screen.DevicePrinterPanel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author adrianromero
 */
public class JPanelPrinter extends JPanel implements JPanelView {

    private final AppView appView;
    
    public JPanelPrinter(AppView appView) {
       
        this.appView = appView;
        initComponents();
        initComponentExtras();
    }
    
    /**
     * Executes post-constructor UI assemblies, components bindings, 
     * and custom layout actions.
     */
    private void initComponentExtras() {
        if (appView.getDeviceTicket().getDeviceDisplay() instanceof DeviceDisplayPanel deviceDisplay) {
            displayJPanel.add(deviceDisplay);
        }     
        
        List<DevicePrinter> printers = appView.getDeviceTicket().getDevicePrinterAll();
        for (int i = 0; i < printers.size(); i++) {   
            DevicePrinter printer = printers.get(i);
            if (printer.getPrinterComponent() != null) {
                printersJTabbedPane.add(printer.getPrinterName(), printer.getPrinterComponent());
            }
        }
        
        DeviceFiscalPrinter fiscalPrinter = appView.getDeviceTicket().getFiscalPrinter();
        if (fiscalPrinter.getFiscalComponent() != null) {
            printersJTabbedPane.add(fiscalPrinter.getFiscalName(), fiscalPrinter.getFiscalComponent());
        }

        // Creates a dedicated horizontal banner panel at the top container area
        JPanel actionContainerPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        
        // Build the control button option to clear ticket views histories
        JButton clearScreensButton = new JButton(AppLocal.getIntString("button.clearscreens") != null ? 
                AppLocal.getIntString("button.clearscreens") : "Clear Screens");
        clearScreensButton.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        
        // Wire the click event action to loop and reset screens
        clearScreensButton.addActionListener(e -> handleClearScreensAction());
        
        actionContainerPanel.add(clearScreensButton);
        add(actionContainerPanel, BorderLayout.SOUTH);
    }
    
     /**
     * Scans the structural active component tab tree searching for active 
     * DevicePrinterPanel wrappers to clear rendered screen queues.
     */
    private void handleClearScreensAction() {
        int tabCount = printersJTabbedPane.getTabCount();
        for (int i = 0; i < tabCount; i++) {
            Component tabComponent = printersJTabbedPane.getComponentAt(i);
            if (tabComponent instanceof DevicePrinterPanel devicePrinterPanel) {
                devicePrinterPanel.reset();
            }
        }
    }

    /**
     *
     * @return
     */
    @Override
    public JComponent getComponent() {
        return this;
    }

    /**
     *
     * @return
     */
    @Override
    public String getTitle() {
        return AppLocal.getIntString("Menu.Printer");
    }        

    /**
     *
     * @throws BasicException
     */
    @Override
    public void activate() throws BasicException {
    }

    /**
     *
     * @return
     */
    @Override
    public boolean deactivate() {
        return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJPanel = new javax.swing.JPanel();
        printersJPanel = new javax.swing.JPanel();
        printersJTabbedPane = new javax.swing.JTabbedPane();

        setPreferredSize(new java.awt.Dimension(480, 600));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());
        add(displayJPanel, java.awt.BorderLayout.NORTH);

        printersJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        printersJPanel.setLayout(new java.awt.BorderLayout());

        printersJTabbedPane.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        printersJPanel.add(printersJTabbedPane, java.awt.BorderLayout.CENTER);

        add(printersJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JPanel printersJPanel;
    private javax.swing.JTabbedPane printersJTabbedPane;
    // End of variables declaration//GEN-END:variables
    
}
