/*
 * Copyright (C) 2022 KriolOS
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.openbravo.pos.printer.screen;

import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.printer.DevicePrinter;
import com.openbravo.pos.printer.ticket.BasicTicket;
import com.openbravo.pos.printer.ticket.BasicTicketForScreen;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.swing.JComponent;
import javax.swing.JScrollPane;

/**
 *
 * @author JG uniCenta
 */
public class DevicePrinterPanel extends javax.swing.JPanel implements DevicePrinter {
    
    private final String printerName;
   
    private final JTicketContainer ticketContainer;    
    private BasicTicket currentTicket;
    

    public DevicePrinterPanel() {
        initComponents();
        
        printerName = AppLocal.getIntString("printer.screen");
        
        currentTicket = null;
       
        ticketContainer = new JTicketContainer();
        m_jScrollView.setViewportView(ticketContainer); 
        m_jScrollView.getVerticalScrollBar().setValue(0);
        m_jScrollView.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
    }
    
    /**
     * @return The localized name of the screen printer
     */
    @Override
    public String getPrinterName() {
        return printerName;
    }
    
    /**
     *
     */
    @Override
    public void printLogo(){   
        // No logo implementation needed for screen preview
    }

    /**
     *
     * @return
     */
    @Override
    public String getPrinterDescription() {
        return null;
    }       

    /**
     *
     * @return
     */
    @Override
    public JComponent getPrinterComponent() {
        return this;
    }

    /**
     *
     */
    @Override
    public void reset() {
        currentTicket = null;
        ticketContainer.removeAllTickets();
        ticketContainer.repaint();
    }
    
    @Override
    public void beginReceipt() {
        currentTicket = new BasicTicketForScreen();

    }

    /**
     *
     * @param image
     */
    @Override
    public void printImage(BufferedImage image) {
        if (currentTicket != null) {
            currentTicket.printImage(image);
        }
    }

    /**
     *
     * @param type
     * @param position
     * @param code
     */
    @Override
    public void printBarCode(String type, String position, String code) {
        if (currentTicket != null) {
            currentTicket.printBarCode(type, position, code);
        }
    }

    @Override
    public void printQRCode(String code, int size, char errorCorrection) {
        if (currentTicket != null) {
            currentTicket.printQRCode(code, size, errorCorrection);
        }
    }

    /**
     *
     * @param textSize
     */
    @Override
    public void beginLine(int textSize) {
        if (currentTicket != null) {
            currentTicket.beginLine(textSize);
        }
    }

    /**
     *
     * @param style
     * @param text
     */
    @Override
    public void printText(int style, String text) {
        if (currentTicket != null) {
            currentTicket.printText(style, text);
        };
    }

    /**
     *
     */
    @Override
    public void endLine() {
        if (currentTicket != null) {
            currentTicket.endLine();
        }
    } 

    /**
     *
     */
    @Override
    public void endReceipt() {
        if (currentTicket != null) {
            ticketContainer.addTicket(new JTicket(currentTicket));
            currentTicket = null;
        }
    }
    
    /**
     *
     */
    @Override
    public void openDrawer() {
        Toolkit.getDefaultToolkit().beep();
    }   
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jScrollView = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        m_jScrollView.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        add(m_jScrollView, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane m_jScrollView;
    // End of variables declaration//GEN-END:variables
    
}
