/*
 * Copyright (C) 2022 KriolOS
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.openbravo.pos.printer.screen;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  Adrian
 */
public class JTicketContainer extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private int H_GAP = 8;
    private int V_GAP = 8;
    private int lastVerticalPosition = 0;
    private final int screenWidth;
    
    public JTicketContainer() {
        initComponents();
         GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.screenWidth = ((ge.getScreenDevices()).length == 1) ? (Toolkit.getDefaultToolkit().getScreenSize()).width : ge.getDefaultScreenDevice().getDisplayMode().getWidth();
    }

    @Override
    public Dimension getPreferredSize() { 
        
       Insets ins = getInsets();
        int iMaxx = 0;
        int iMaxy = ins.top + this.V_GAP;
        int n = getComponentCount();
        for (int i = 0; i < n; i++) {
            Component comp = getComponent(i);
            Dimension dc = comp.getPreferredSize();
            if (dc.width > iMaxx) {
                iMaxx = dc.width;
            }
            iMaxy += this.V_GAP + dc.height;
        }
        return new Dimension(iMaxx + 2 * this.H_GAP + ins.left + ins.right, iMaxy + ins.bottom);
    }

    @Override
    public Dimension getMaximumSize() {
      return getPreferredSize();
    }

    @Override
    public Dimension getMinimumSize() {
      return getPreferredSize();
    }

    @Override
    public void doLayout() {
        Insets ins = getInsets();
        int x = ins.left + this.H_GAP;
        int y = ins.top + this.V_GAP;
        int columns = this.screenWidth / (getPreferredSize()).width;
        int iMaxy = 0;
        int iMaxx = 0;
        int numComponents = getComponentCount();
        for (int pos = 0; pos < numComponents; pos++) {
            Component comp = getComponent(pos);
            Dimension dc = comp.getPreferredSize();
            comp.setBounds(x, y, dc.width, dc.height);
            x += this.H_GAP + dc.width;
            if (dc.height > iMaxy) {
                iMaxy = dc.height;
            }
            if ((pos + 1) % columns == 0) {
                x = ins.left + this.H_GAP;
                y += this.V_GAP + iMaxy;
                iMaxy = 0;
            }
            
            lastVerticalPosition = y;
        }
    }
    
    public void addTicket(JTicket ticket) {
        add(ticket);
        doLayout();
        revalidate();
        scrollRectToVisible(new Rectangle(0, lastVerticalPosition, 1, 1));
    }
    
    public void removeAllTickets() {
        removeAll();
        doLayout();
        revalidate();
        scrollRectToVisible(new Rectangle(0, 0, 1, 1));   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 600));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
