/*
 * Copyright (C) 2022 KriolOS
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.openbravo.pos.printer.screen;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * Container panel that stores and dynamically positions JTicket view components.
 * Fixed arithmetic calculations and structured for safe Swing rendering.
 * 
 * @author Adrian
 * @author KriolOS
 */
public class JTicketContainer extends JPanel {

    private static final long serialVersionUID = 1L;

    private static final int HORIZONTAL_GAP = 8;
    private static final int VERTICAL_GAP = 8;
    
    private int lastVerticalPosition = 0;
    private final int screenWidth;
    
    public JTicketContainer() {
        initComponents();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.screenWidth = (ge.getScreenDevices().length == 1) 
                ? Toolkit.getDefaultToolkit().getScreenSize().width 
                : ge.getDefaultScreenDevice().getDisplayMode().getWidth();
    }

    @Override
    public Dimension getPreferredSize() { 
        Insets ins = getInsets();
        int maxComponentWidth = 0;
        int accumulatedHeight = ins.top + VERTICAL_GAP;
        int componentCount = getComponentCount();
        
        for (int i = 0; i < componentCount; i++) {
            Component comp = getComponent(i);
            Dimension dc = comp.getPreferredSize();
            if (dc.width > maxComponentWidth) {
                maxComponentWidth = dc.width;
            }
            accumulatedHeight += VERTICAL_GAP + dc.height;
        }
        
        int totalWidth = maxComponentWidth + (2 * HORIZONTAL_GAP) + ins.left + ins.right;
        int totalHeight = accumulatedHeight + ins.bottom;
        
        return new Dimension(Math.max(totalWidth, 700), Math.max(totalHeight, 600));
    }

    @Override
    public Dimension getMaximumSize() {
        return getPreferredSize();
    }

    @Override
    public Dimension getMinimumSize() {
        return getPreferredSize();
    }

    @Override
    public void doLayout() {
        Insets ins = getInsets();
        int x = ins.left + HORIZONTAL_GAP;
        int y = ins.top + VERTICAL_GAP;
        
        int preferredWidth = getPreferredSize().width;
        // Prevent division by zero or negative sizing columns
        int columns = (preferredWidth > 0) ? (this.screenWidth / preferredWidth) : 1;
        if (columns <= 0) {
            columns = 1;
        }
        
        int maxRowHeight = 0;
        int numComponents = getComponentCount();
        
        for (int pos = 0; pos < numComponents; pos++) {
            Component comp = getComponent(pos);
            Dimension dc = comp.getPreferredSize();
            comp.setBounds(x, y, dc.width, dc.height);
            
            x += HORIZONTAL_GAP + dc.width;
            if (dc.height > maxRowHeight) {
                maxRowHeight = dc.height;
            }
            
            if ((pos + 1) % columns == 0) {
                x = ins.left + HORIZONTAL_GAP;
                y += VERTICAL_GAP + maxRowHeight;
                maxRowHeight = 0;
            }
            
            lastVerticalPosition = y + dc.height;
        }
    }
    
    public void addTicket(JTicket ticket) {
        add(ticket);
        revalidate();
        repaint();
        
        // Safely scroll down after layout execution on EDT
        SwingUtilities.invokeLater(() -> 
            scrollRectToVisible(new Rectangle(0, lastVerticalPosition, 1, 1))
        );
    }
    
    public void removeAllTickets() {
        removeAll();
        revalidate();
        repaint();
        scrollRectToVisible(new Rectangle(0, 0, 1, 1));   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 600));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
